sudo: false

language:
  - python

python:
  - 2.7
  - 3.6

install:
  - pip install pycodestyle
  - pip install -r requirements.txt

script:
  - pycodestyle mdn --ignore=E501
  - pytest --verbose --capture=no mdn
  - pip install .

notifications:
  email: false
